/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    CodeEditor: typeof import('./src/components/element/pages/ide/editor/CodeEditor.vue')['default']
    CodeTabContent: typeof import('./src/components/element/pages/ide/codetabs/CodeTabContent.vue')['default']
    CodeTabs: typeof import('./src/components/element/pages/ide/CodeTabs.vue')['default']
    DropdownMenu: typeof import('./src/components/ui/dropdown-menu/DropdownMenu.vue')['default']
    DropdownMenuCheckboxItem: typeof import('./src/components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue')['default']
    DropdownMenuContent: typeof import('./src/components/ui/dropdown-menu/DropdownMenuContent.vue')['default']
    DropdownMenuGroup: typeof import('./src/components/ui/dropdown-menu/DropdownMenuGroup.vue')['default']
    DropdownMenuItem: typeof import('./src/components/ui/dropdown-menu/DropdownMenuItem.vue')['default']
    DropdownMenuLabel: typeof import('./src/components/ui/dropdown-menu/DropdownMenuLabel.vue')['default']
    DropdownMenuRadioGroup: typeof import('./src/components/ui/dropdown-menu/DropdownMenuRadioGroup.vue')['default']
    DropdownMenuRadioItem: typeof import('./src/components/ui/dropdown-menu/DropdownMenuRadioItem.vue')['default']
    DropdownMenuSeparator: typeof import('./src/components/ui/dropdown-menu/DropdownMenuSeparator.vue')['default']
    DropdownMenuShortcut: typeof import('./src/components/ui/dropdown-menu/DropdownMenuShortcut.vue')['default']
    DropdownMenuSub: typeof import('./src/components/ui/dropdown-menu/DropdownMenuSub.vue')['default']
    DropdownMenuSubContent: typeof import('./src/components/ui/dropdown-menu/DropdownMenuSubContent.vue')['default']
    DropdownMenuSubTrigger: typeof import('./src/components/ui/dropdown-menu/DropdownMenuSubTrigger.vue')['default']
    DropdownMenuTrigger: typeof import('./src/components/ui/dropdown-menu/DropdownMenuTrigger.vue')['default']
    EdgeContainer: typeof import('./src/components/element/pages/ide/EdgeContainer.vue')['default']
    FileSettingItem: typeof import('./src/components/element/pages/ide/topmenu-items/FileSettingItem.vue')['default']
    FooterStatusBar: typeof import('./src/components/element/pages/ide/FooterStatusBar.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IdeEditor: typeof import('./src/components/element/pages/ide/IdeEditor.vue')['default']
    MainContent: typeof import('./src/components/element/pages/ide/MainContent.vue')['default']
    MainFrame: typeof import('./src/components/element/pages/ide/MainFrame.vue')['default']
    NSplit: typeof import('naive-ui')['NSplit']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTree: typeof import('naive-ui')['NTree']
    ProjTree: typeof import('./src/components/element/pages/ide/ProjTree.vue')['default']
    Providers: typeof import('./src/components/providers/Providers.vue')['default']
    ResizableHandle: typeof import('./src/components/ui/resizable/ResizableHandle.vue')['default']
    ResizablePanelGroup: typeof import('./src/components/ui/resizable/ResizablePanelGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollArea: typeof import('./src/components/ui/scroll-area/ScrollArea.vue')['default']
    ScrollBar: typeof import('./src/components/ui/scroll-area/ScrollBar.vue')['default']
    SiderBar: typeof import('./src/components/element/pages/ide/SiderBar.vue')['default']
    TopMenu: typeof import('./src/components/element/pages/ide/TopMenu.vue')['default']
    TopMenuItemBase: typeof import('./src/components/element/pages/ide/topmenu-items/TopMenuItemBase.vue')['default']
    VmIde: typeof import('./src/components/element/VmIde.vue')['default']
    VscodeIconsFileTypePython: typeof import('./src/components/icons/VscodeIconsFileTypePython.vue')['default']
    WebIdeProviders: typeof import('./src/components/providers/WebIdeProviders.vue')['default']
  }
}
