/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CodeEditor: typeof import('./src/components/element/pages/ide/editor/CodeEditor.vue')['default']
    FooterStatusBar: typeof import('./src/components/element/pages/ide/FooterStatusBar.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IdeEditor: typeof import('./src/components/element/pages/ide/IdeEditor.vue')['default']
    MainContent: typeof import('./src/components/element/pages/ide/MainContent.vue')['default']
    MainFrame: typeof import('./src/components/element/pages/ide/MainFrame.vue')['default']
    NSplit: typeof import('naive-ui')['NSplit']
    NTree: typeof import('naive-ui')['NTree']
    ProjTree: typeof import('./src/components/element/pages/ide/ProjTree.vue')['default']
    Providers: typeof import('./src/components/providers/Providers.vue')['default']
    ResizableHandle: typeof import('./src/components/ui/resizable/ResizableHandle.vue')['default']
    ResizablePanelGroup: typeof import('./src/components/ui/resizable/ResizablePanelGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollArea: typeof import('./src/components/ui/scroll-area/ScrollArea.vue')['default']
    ScrollBar: typeof import('./src/components/ui/scroll-area/ScrollBar.vue')['default']
    SiderBar: typeof import('./src/components/element/pages/ide/SiderBar.vue')['default']
    TopMenu: typeof import('./src/components/element/pages/ide/TopMenu.vue')['default']
    VmIde: typeof import('./src/components/element/VmIde.vue')['default']
    WebIdeProviders: typeof import('./src/components/providers/WebIdeProviders.vue')['default']
  }
}
