export const IDE_CMD_TYPES = {
  IDE_LIST_PROJECTS: 'ide_list_projects',
  IDE_GET_PROJECT: 'ide_get_project',
  IDE_CREATE_PROJECT: 'ide_create_project',
  IDE_DEL_PROJECT: 'ide_delete_project',
  IDE_RENAME_PROJECT: 'ide_rename_project',
  IDE_SAVE_PROJECT: 'ide_save_project',
  IDE_CREATE_FILE: 'ide_create_file',
  IDE_WRITE_FILE: 'ide_write_file',
  IDE_GET_FILE: 'ide_get_file',
  IDE_DEL_FILE: 'ide_delete_file',
  IDE_RENAME_FILE: 'ide_rename_file',
  IDE_CREATE_FOLDER: 'ide_create_folder',
  IDE_DEL_FOLDER: 'ide_delete_folder',
  IDE_RENAME_FOLDER: 'ide_rename_folder',
  IDE_AUTOCOMPLETE_PYTHON: 'autocomplete_python',
  IDE_RUN_PIP_COMMAND: 'run_pip_command',
  IDE_RUN_PYTHON_PROGRAM: 'run_python_program',
  IDE_STOP_PYTHON_PROGRAM: 'stop_python_program',
  IDE_GET_PYTHON_PKG_INSTALLED_LIST: 'get_python_pkg_installed_list',
  IDE_INSTALL_PYTHON_PACKAGE: 'install_python_package',
  IDE_INSTALL_PY_PKG_BY_LOCAL_FILE: 'install_py_pkg_by_local_file'
};
