// This file is auto-generated by @hey-api/openapi-ts

export const $ResponseBase = {
    properties: {
        type: {
            type: 'string',
            title: 'Type',
            default: 'response'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        code: {
            type: 'integer',
            title: 'Code',
            default: 0
        },
        data: {
            anyOf: [
                {
                    type: 'object'
                },
                {
                    items: {},
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data'
        }
    },
    type: 'object',
    required: ['id'],
    title: 'ResponseBase'
} as const;