// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { $OpenApiTs } from './types.gen';

export class IdeService {
    /**
     * Ide List Projects
     * @returns ResponseBase Successful Response
     * @throws ApiError
     */
    public static ideIdeListProjects(): CancelablePromise<$OpenApiTs['/api/v1/ide_list_projects']['get']['res'][200]> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/ide_list_projects'
        });
    }
    
}