// This file is auto-generated by @hey-api/openapi-ts

export type ResponseBase = {
    type?: string;
    id: number;
    code?: number;
    data?: {
    [key: string]: unknown;
} | Array<unknown> | null;
};

export type $OpenApiTs = {
    '/api/v1/ide_list_projects': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
            };
        };
    };
};