// This file is auto-generated by @hey-api/openapi-ts

export type CreateFileItem = {
    projectName: string;
    parentPath: string;
    fileName: string;
};

export type CreateFolderItem = {
    projectName: string;
    parentPath: string;
    folderName: string;
};

export type DeleteFolderItem = {
    projectName: string;
    folderPath: string;
};

export type FileItem = {
    projectName: string;
    filePath: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ProjItem = {
    projectName: string;
};

export type ProjReNameItem = {
    oldName: string;
    newName: string;
};

export type ReNameItem = {
    projectName: string;
    oldPath: string;
    newName: string;
};

export type ResponseBase = {
    type?: string | null;
    id?: number | null;
    code?: number;
    data: unknown;
};

export type SaveProjItem = {
    projectName: string;
    expendKeys: Array<unknown>;
    openList: Array<unknown>;
    selectFilePath: string | null;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WriteFileItem = {
    projectName: string;
    filePath: string;
    fileData: string;
    complete?: boolean | null;
    line?: number | null;
    column?: number | null;
};

export type $OpenApiTs = {
    '/api/v1/ide/ide_list_projects': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
            };
        };
    };
    '/api/v1/ide/ide_get_project': {
        post: {
            req: {
                requestBody: ProjItem;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/ide/ide_create_project': {
        post: {
            req: {
                requestBody: ProjItem;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/ide/ide_delete_project': {
        post: {
            req: {
                requestBody: ProjItem;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/ide/ide_rename_project': {
        post: {
            req: {
                requestBody: ProjReNameItem;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/ide/ide_save_project': {
        post: {
            req: {
                requestBody: SaveProjItem;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/ide/ide_create_file': {
        post: {
            req: {
                requestBody: CreateFileItem;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/ide/ide_write_file': {
        post: {
            req: {
                requestBody: WriteFileItem;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/ide/ide_get_file': {
        post: {
            req: {
                requestBody: FileItem;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/ide/ide_delete_file': {
        post: {
            req: {
                requestBody: FileItem;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/ide/ide_rename_file': {
        post: {
            req: {
                requestBody: ReNameItem;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/ide/ide_create_folder': {
        post: {
            req: {
                requestBody: CreateFolderItem;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/ide/ide_delete_folder': {
        post: {
            req: {
                requestBody: DeleteFolderItem;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/ide/ide_rename_folder': {
        post: {
            req: {
                requestBody: ReNameItem;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/ide/get_python_pkg_installed_list': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
            };
        };
    };
};